name: Deploy Django Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy on EC2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add Environment Variables
        run: |
          echo "${{vars.ENV}}" > .env
      - name: Run Gunicorn
        run: |
          source venv/bin/activate
          gunicorn bd.wsgi:application --config prod.py
